### ISSUE TITLE
Set up email forwarding for system emails

### ISSUE THREAD

**Issue by mkllnk** [ceresfairfood/fairfood-install#13]
System emails are currently in the root user's inbox. We can forward them with a `.forward` file but we need to make sure that the server is authorised to send those emails.

**Comment by dacook** [comment]
I've done this manually, forwarding to ceresfairfood+it@openfoodnetwork.org.au

Unfortunately I found that it doesn't rewrite the "to:" address in the email header, which makes it a bit hard to filter in my email client. 
![Screen Shot 2022-04-20 at 12 14 30 pm](https://user-images.githubusercontent.com/4188088/164133315-67175cf0-d08c-47fe-b2c7-0a878d350831.png)

I think I could set up a mapping like this: http://www.postfix.org/ADDRESS_REWRITING_README.html#canonical 
But meh.
